[
	| a b c d e f g h i j |

	a := 1.
	b := 2.
	c := 3.
	d := 4.
	e := 5.
	f := 6.
	g := 7.
	h := 8.
	i := 9.
	j := 10.

	a + b + c + d + e + f + g + h + i + j.

	a := b.
	a := c.
	a := d.
	a := e.
	a := f.
	a := g.
	a := h.
	a := i.
	a := j.

	b := a.
	b := c.
	b := d.
	b := e.
	b := f.
	b := g.
	b := h.
	b := i.
	b := j.

	c := a.
	c := b.
	c := d.
	c := e.
	c := f.
	c := g.
	c := h.
	c := i.
	c := j.

	d := a.
	d := b.
	d := c.
	d := e.
	d := f.
	d := g.
	d := h.
	d := i.
	d := j.

	d := a.
	d := b.
	d := c.
	d := e.
	d := f.
	d := g.
	d := h.
	d := i.
	d := j.

	j := a.
	j := b.
	j := c.
	j := d.
	j := e.
	j := f.
	j := g.
	j := h.
	j := i.

	a + b + c + d + e + f + g + h + i + j.
]
